### ISSUE TITLE
dcma can strike

### ISSUE THREAD

**Issue by dsslimshaddy** [beaston02/ChaturbateRecorder#10]

**Comment by beaston02** [comment]
Do you mean DMCA?

If so, this has nothing to do with DMCA, this is for capturing publicly broadcast webcam sessions, not sharing or hosting the files online.

**Comment by beaston02** [comment]
Im closing this because Im not sure what youre getting at since there is no description, and no reply. Please feel free to reopen if you want to add to it. 

Thank you!
