### ISSUE TITLE
error

### ISSUE THREAD

**Issue by orchid666** [beaston02/ChaturbateRecorder#11]
Tried to run the script, got this error:

File "ChaturbateRecorder.py", line 133
    print("the following models are being recorded: {}".format(recording), end="\r")
                                                                              ^
SyntaxError: invalid syntax

Am I missing something?

**Comment by beaston02** [comment]
Make sure you're running it with python3.5 or newer. I believe this error will occur if you're using earlier versions of Python. 

This has came up before and some things I've found is users would install python3.5 and not realize it doesn't replace earlier versions of Python, so they would run it with "python ChaturabateRecorder.py" effectively running it with python2.7. Python3.5 + is generally called with "python3" or "python3.5" as supposed to just "python"

I'm replying from my phone, so please excuse any typos or autocorrects.

**Comment by orchid666** [comment]
Thanks! I installed python3 but i forgot to restart my terminal. It's recording now, I need to explore all the options now :)
Thanks a lot, good work!

**Comment by beaston02** [comment]
Im glad you got it going! If you have any other issues, or questions let me know! 

Enjoy!
