### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by jeffkerby** [beaston02/ChaturbateRecorder#16]
I wanted to first say this is a great script you created and I have been using it for some time now without any problems. However,  after downloading your latest version last night the script no longer works. I rolled back to a July version and it works fine. You may want to check to see what's up.

Thanks

**Comment by beaston02** [comment]
Thanks for the feedback!

Youre not getting any errors or anything? whats your output? 

I just tested on my computer, and it immediately started recording models with no problem.

**Comment by jeffkerby** [comment]
No errors - just saying, zero models, online is all and keeps going through the cycle every 20 seconds. The old version still running fine for the last several hours.
