### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by longsack** [beaston02/ChaturbateRecorder#23]
Okay... in an effort to fix my other issues I installed debian 8.... and have a new setup.

I'm getting the following error now when I run "python3.6 ChaturbateRecorder.py":

Traceback (most recent call last):
  File "/usr/lib/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'wishlist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ChaturbateRecorder.py", line 13, in <module>
    wishlist = Config.get('paths', 'wishlist')
  File "/usr/lib/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'wishlist' in section: 'paths'
root@ns354086:/var/www/clients/client1/web1/web/recorders/cb#

**Comment by beaston02** [comment]
What does your config file look like? Is it in the same directory as the ChaturbateRecorder.py? 

That error is saying there isn't a "wishlist" setting in the paths section (under "[paths]" in the config file)

I may do a complete rewrite on this script using classes and hopefully that will help with the duplicate recordings issue. I still don't see what's causing it, and I also haven't ran into it myself for whatever reason (I only run it for testing purposes right now though, so maybe I'm not recording enough models)

**Comment by longsack** [comment]
please close... I screwed up the config file... i made changes and uploaded the wrong one.

**Comment by longsack** [comment]
sorry and thank you so much!

**Comment by beaston02** [comment]
No worries, I thought that was maybe the case. We've all made that same mistake before ;) 

I'm glad it was an easy fix!

**Comment by longsack** [comment]
but I am having issues with mfcrecorder... i will check some issues before I post... bascially i'm not getting my "tags" or other to record.  will check issues/and closed issues 1st before I post.  also check other screw ups I may have made.

**Comment by beaston02** [comment]
I haven't noticed any issues with the tags (also running MFC for testing, and tags is what's doing the majority of the recording for me). I also haven't heard any issues. I would look at the config file for that also. 

Each tag should be separated by a comma, and spaces between them is also fine (ie: "big boobs, fit, brunette, milf, cum" (without the quotes)) - it is not case sensitive so don't need to do things like "MILF, milf, Milf". You need to make sure to have the minimum number of tags set. There is also the setting for minimum viewers for the tag condition. If that is set too high, it won't catch many models (I don't use that setting myself, I leave it at 0). Personally, I think a better method than using the minimum viewers is to be less aggressive, and maybe start with about 4 or 5 tags, and a minimum of say 2 must be met. disable models you don't want to record who are met with those conditions, and maybe add more tags if you want to catch more from there, and repeat. From what I've noticed, there are some models who get surprisingly few viewers and just kind of fly under the radar. They would be missed with any reasonable general minimum viewer setting. 

 As long as you have the config file correct, it should work. If you do create an issue, please include that portion of your config file in it so I can see if I notice anything there.
