### ISSUE TITLE
ImportModels.py - list index out of range

### ISSUE THREAD

**Issue by benben2033** [beaston02/ChaturbateRecorder#28]
runnynin ImportModels.py stops work for me few days ago, getting this error, before that it worked like a charm

`logged in
getting followed models...
Traceback (most recent call last):
  File "ImportFollowed.py", line 74, in <module>
    getModels()
  File "ImportFollowed.py", line 59, in getModels
    if int(soup.findAll('li', {'class': 'active'})[1].string) >= int(soup.findAll('a', {'class': 'endless_page_link'})[-2].string):
IndexError: list index out of range
`

**Comment by beaston02** [comment]
I just posted an update. The script worked fine on my end prior to making the change, so Im not 100% sure this will fix it, but I assume it will. 

My account has several pages of followed models, and I'm guessing the error was caused when only a single page of models is being followed as it seems the error was related to it checking which page it was on. 

Please let me know if the update fixed the problem for you.

**Comment by benben2033** [comment]
thx, its working
yes I removed lots of followed models so that was probably the reason :)
