### ISSUE TITLE
Can't seem to capture models from the wishlist

### ISSUE THREAD

**Issue by morethanwysiwyg** [beaston02/ChaturbateRecorder#4]
I have followed the instructions - installed Python 3.5 and dependancies, created new folder for the recordings, created wishlist with one line (full url) of model, and set gender = female.

I can't seem to get any models to record. Am I doing something wrong? Please see below:

wanted.txt:
`https://chaturbate.com/placeholderForModelName/`

config.conf:
`[paths]
wishlist = /Library/WebServer/Documents/images/LiveChat/wanted.txt
save_directory = /Library/WebServer/Documents/images/LiveChat/cbr/

[settings]
checkInterval = 20
genders = female`

The files and and folders exist but when I run it, it always says:
`0 model(s) are being recorded. Next check in 18 seconds . the following models are being recorded: []`

The timer keeps counting, but I know the model is online, I have tried with different models, and OS X 910.9.5 and 10.12.5 with the same results. Any suggestions?

**Comment by beaston02** [comment]
If I'm reading it correctly, you are including the entire URL, not just the models name? If so, that is the problem. It should only be the models name as it appears in the URL. 

I just updated the readme to hopefully make that more clear as you are not the first person to have this issue. I will probably go ahead and update the script to allow for full URL also, to avoid this problem in the future. 

Please let me know if this fixes the problem for you.

**Comment by morethanwysiwyg** [comment]
Yep. that was it. It works with just the model's name.
Thank you!

**Comment by beaston02** [comment]
Great, I'm glad that fixed it. 

In case you didn't see the other issue on here (#1 I believe), some users are experiencing a "too many open files" error which I'm currently working on a fix for. I personally have not experienced it on my Mac, so maybe OS X handles it better for some reason, but a work around is to set the ulimit to a greater value. This is a "bandaid" solution, but one that prolongs the problem.
