### ISSUE TITLE
Not Starting

### ISSUE THREAD

**Issue by MrOctober77** [beaston02/ChaturbateRecorder#51]
Trying to run it, get this error:

python ChaturbateRecorder.py
  File "ChaturbateRecorder.py", line 120
    print("the following models are being recorded: {}".format(recording), end="\r")
                                                                              ^
SyntaxError: invalid syntax

I have the model in the wanted list.

The record path and wanted.text path are set correctly.

**Comment by Nytelife26** [comment]
What version of Python are you using?

**Comment by MrOctober77** [comment]
Nevermind, I needed to start it with python3 instead of just python
