### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Tisha563** [beaston02/ChaturbateRecorder#7]
Hello, 

I'm trying to get your script working but I always getting these error : 
`python ChaturbateRecorder.py
  File "ChaturbateRecorder.py", line 81
    print("the following models are being recorded: {}".format(recording), end="\r")
                                                                              ^
SyntaxError: invalid syntax
`
Do you know where it come from ? 

Thanks ! :)

**Comment by beaston02** [comment]
Are you for sure running it with Python 3.5 or newer? 

I believe that error would occur if it was being ran with anything less. Otherwise, I can't think of anything else that would cause it.

**Comment by Tisha563** [comment]
You're right, I have some issue with Python : 
root@ns:/ChaturbateRecorder-master# python --version
Python 2.7.13
root@ns:/ChaturbateRecorder-master# python3.5 --version
Python 3.5.3

Thanks ;)

**Comment by beaston02** [comment]
You can of have multiple versions of Python installed, and it's really rather normal to have multiple versions. Instead of running it with "python ChaturbateRecorder.py" do it with "python3.5 ChaturbateRecorder.py"

That should fix your problem

**Comment by Tisha563** [comment]
Its working now, thanks ;)

**Comment by beaston02** [comment]
Good to hear! I'll close this issue then. Enjoy!
