### ISSUE TITLE
config.conf missing lines

### ISSUE THREAD

**Issue by JoshTheBlack** [beaston02/ChaturbateRecorder#8]
The config.conf is missing some lines.  I did a git --reset hard origin/master to make sure I was up to current and the script wouldn't run.

The config file is missing (at a minimum):
```
[paths]
save_directory = /path/to/save/directory/
wishlist = wanted.txt
```

Probably some instructional stuff too.

**Comment by beaston02** [comment]
Good catch! thank you. I meant to copy/paste the changes only, (which I did), but then pasted over the entire document removing those lines! 

It is now fixed. Thanks again
